name: Display variable in console

on: 
  push:
    branches:
      - main

jobs:
  display-variable-job:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Display variable
        run: |
          echo "My variable value is : ${{ vars.VARIABLE_GREETING }}"
      
      - name: Display secret
        run: |
          echo "My secret value is: ${{ secrets.SECRET_GREETING }}"
  
  display-prod-variable-job:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Display variable
        run: |
          echo "My variable value is : ${{ vars.VARIABLE_GREETING }}"
      
      - name: Display secret
        run: |
          echo "My secret value is: ${{ secrets.SECRET_GREETING }}"
